# REDIS CONFIGURATIONS
%dev.quarkus.redis.hosts=redis://localhost:6379
%test.quarkus.redis.devservices.enabled=true
%prod.quarkus.redis.hosts=${REDIS_CONNECTION_STRING}

# MONGODB CONFIGURATIONS
%dev.quarkus.mongodb.connection-string=mongodb://localhost:27017
%dev.quarkus.mongodb.database=trello-clone
%test.quarkus.mongodb.database=trello-clone-test
%test.quarkus.mongodb.devservices.enabled=true
%prod.quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING}
%prod.quarkus.mongodb.database=${MONGODB_DATABASE_NAME}
quarkus.mongodb.dns.lookup-timeout=200S
quarkus.mongodb.dns.log-activity=true
quarkus.naming.enable-jndi=true

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=*
quarkus.http.cors.access-control-allow-credentials=true

# SWAGGER API
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Trello Clone API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Backend REST API for a Trello-like board management system. Built with Quarkus, MongoDB and Redis.
quarkus.smallrye-openapi.info-contact-name=Fabio Porzio
quarkus.smallrye-openapi.info-contact-url=https://github.com/fabioporzio
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=BearerAuth
quarkus.smallrye-openapi.security-scheme-description=JWT Bearer token

# JWT

# Demo keys replaced by environment configuration in production.
mp.jwt.verify.issuer=trello-clone-jwt
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

# RATE LIMITERS
quarkus.rate-limiter.buckets.search.limits[0].permitted-uses=10
quarkus.rate-limiter.buckets.search.limits[0].period=1S
quarkus.rate-limiter.buckets.search.limits[1].permitted-uses=100
quarkus.rate-limiter.buckets.search.limits[1].period=5M

# Login Rate Limiters definitions
%test.quarkus.rate-limiter.buckets.login.limits[0].permitted-uses=100000
%test.quarkus.rate-limiter.buckets.login.limits[1].permitted-uses=100000
quarkus.rate-limiter.buckets.login.limits[0].permitted-uses=5
quarkus.rate-limiter.buckets.login.limits[0].period=1M
quarkus.rate-limiter.buckets.login.limits[1].permitted-uses=20
quarkus.rate-limiter.buckets.login.limits[1].period=1H